export const COMMON = {
  SECURITY_GROUP: 'common/SECURITY_GROUP',
  SERVERLESS_DEPLOYMENT_BUCKET: 'COMMON/SERVERLESS_DEPLOYMENT_BUCKET',
  SUBNET_1: 'common/SUBNET_1',
  SUBNET_2: 'common/SUBNET_2',
  REDIS_HOST: 'common/REDIS_HOST',
  REDIS_PORT: 'common/REDIS_PORT',
  MYSQL_HOST: 'MYSQL/HOST',
  MYSQL_PORT: 'MYSQL/PORT'
}

export const QUEUE_NAMES = {
  TOOTHSI: 'SALESFORCE_QUEUE/QUEUE_NAME',
  TOOTHSI_ALT: 'SALESFORCE_QUEUE/TOOTHSI_SF_ALT_QUEUE_NAME',
  SKINNSI: 'SALESFORCE_QUEUE/SKINNSI/QUEUE_NAME',
  ECOM: 'SALESFORCE_QUEUE/ECOM/QUEUE_NAME'
}
